In [1]:
%load_ext autoreload
%autoreload 2

In [92]:
from simple_linear_regression import SimpleLinearRegression
from squared_error_loss import SquaredErrorLoss
from gradient_descent import GradientDescent
from supervised_algorithm import SupervisedAlgorithm
from machine_learning_algorithm import MachineLearningAlgorithm
from parameter import Parameter
from numpy import array, genfromtxt, dot, hstack, append, ones, vstack, vdot, inner

In [93]:
p = Parameter()

In [94]:
p.value = 8
p.is_initialized()

True

In [95]:
intercept = 0.
slope = 0.
param_dict = {"intercept": intercept,
        "slope": slope}
hyp = SimpleLinearRegression()

In [96]:
file_name = '../data/input/ex1data1.txt'
data = genfromtxt(file_name, dtype=float, delimiter = ',')
features = data[:,0] # obtains the first column of data
features = features.reshape((len(features), 1)) # reshapes features so that it is of dimension nobs x 1
y = data[:, 1]
y = y.reshape((len(y), 1))

In [97]:
sel = SquaredErrorLoss(hyp, features, y)

In [98]:
sel.initialize_parameters(param_dict)
sel.cost_function_derivative()

array([[ -5.83913505],
       [-65.32884975]])

In [433]:
sel.cost_function_derivative()

array([[ -5.83913505],
       [-65.32884975]])

In [435]:
sel.cost_function()

array([[ 32.07273388]])

In [99]:
gd = GradientDescent(.0001, param_dict, .000000001, sel)

In [101]:
gd.algorithm()

In [102]:
gd.new_cost

array([[ 4.47699911]])

In [103]:
gd.get_parameters()

array([[-3.87832611],
       [ 1.19128012]])

In [38]:
parms_tmp = hstack((gd.get_parameters()[0], gd.get_parameters()[1]))
parms_tmp = parms_tmp.reshape(len(parms_tmp), 1)

In [40]:
parms_tmp.shape

(2, 1)

In [675]:
gd.param_starting_values

{'intercept': 0.0, 'slope': 0.0}

In [676]:
gd.initialize_parameters()

In [781]:
gd.current_cost = gd.cost_function.cost_function()

In [782]:
gd.current_cost

array([[ 8.71934001]])

In [41]:
updated_params = gd.get_parameters() - gd.learning_rate*gd.cost_function.cost_function_derivative()

In [784]:
gd.learning_rate*gd.cost_function.cost_function_derivative()

array([[-0.00143388],
       [-0.02146155]])

In [785]:
gd.cost_function.cost_function_derivative()

array([[ -1.43388311],
       [-21.46154703]])

In [43]:
updated_params.shape

(2, 1)

In [787]:
gd.cost_function.update_parameters(updated_params)

In [788]:
gd.cost_function.cost_function()

array([[ 8.27568536]])

In [488]:
gd.new_cost

In [445]:
gd.get_parameters()

array([[  5.83913505],
       [ 65.32884975]])

In [261]:
sel.initialize_parameters(param_dict)

In [262]:
sel.cost_function_derivative()

array([[  11.48046495],
       [ 105.6388359 ]])

In [263]:
updated_params = sel.get_parameters() - 1.*sel.cost_function_derivative()
updated_params[1]

array([-103.6388359])

In [264]:
sel.update_parameters(updated_params)

In [265]:
sel.get_parameters()

array([[ -10.48046495],
       [-103.6388359 ]])

In [244]:
sel.cost_function()

array([[ 75.20338498]])

In [789]:
gd.algorithm()

In [790]:
gd.get_parameters()

array([[ 0.04996814],
       [ 0.76312424]])

In [135]:
ones(6).reshape(1, 6).shape

(1, 6)

In [4]:
parms = hyp.get_parameters()
parms.shape

(2, 1)

In [5]:
parm_tmp = hstack((intercept, slope))
parm_tmp = parm_tmp.reshape(len(parm_tmp), 1)

In [6]:
parm_tmp

array([[1],
       [2]])

In [61]:
features = data[:,0] # obtains the first column of data
features = features.reshape((len(features), 1)) # reshapes features so that it is of dimension 1 x nobs
#len(features)
#y = data[:, 1]
#y = y.reshape((1, len(y)))
#append(ones(features.shape[0]).reshape(features.shape[0], 1), features, 0).shape
append(ones(features.shape[0]).reshape(features.shape[0], 1), features, 1).shape
#append(ones(features.shape[0]))
#.reshape(features.shape[1], 1), features, 1)
#features1.shape
#features.shape

(97, 2)

In [54]:
features.shape[0]

97

In [14]:
sel = SquaredErrorLoss(hyp, features, y)

In [15]:
sel.cost_function_derivative()

array([[  1113.6051    ,  10246.96708216]])

In [266]:
1/sel.nobs*(sel.hypothesis.hypothesis_function(sel.features) - sel.yvalues).dot((sel.hypothesis.feature_setup(sel.features)).T)
#sel.hypothesis.feature_setup(sel.features).T.shape

array([[  1113.6051    ,  10246.96708216]])

In [288]:
#sel.yvalues.T.dot(sel.yvalues)
#-
sel.yvalues.T.shape.dot(sel.hypothesis.feature_setup(features).T)
#)
#.dot(sel.parameters) 
#- sel.parameters.T.dot(sel.features.T).dot(sel.yvalues) + self.parameters.T.dot(sel.features.T).dot(sel.features).dot(sel.parameters)


(97, 1)

In [255]:
(sel.hypothesis.hypothesis_function(features) - y).dot(features)

ValueError: shapes (1,97) and (1,97) not aligned: 97 (dim 1) != 1 (dim 0)

In [232]:
y.shape

(1, 97)

In [187]:
nobs = features.shape[1]
(1./nobs*tmp.hypothesis_function(features) - y).shape

(1, 97)

In [125]:
data[:, 0].shape

(97,)

In [64]:
parms.T.dot(features)

ValueError: shapes (1,2) and (97,) not aligned: 2 (dim 1) != 97 (dim 0)

In [65]:
parms.dot(features)

ValueError: shapes (2,1) and (97,) not aligned: 1 (dim 1) != 97 (dim 0)

In [164]:
features.shape

(1, 97)

In [80]:
parms.shape

(2, 1)

In [83]:
array([0, 1]).shape

(2,)

In [166]:
features.shape[1]

97

In [39]:
tmp = array([[1], [6]])

In [40]:
tmp[1][0]

6

In [49]:
a = 1.
b = 2.
c = hstack((array(a), array(b)))

In [50]:
c

array([ 1.,  2.])

In [53]:
c.reshape(2, 1).shape

(2, 1)